### ISSUE TITLE
DNS settings not going back to normal after disconnecting

### ISSUE THREAD

**Issue by e9169** [andrewgdotcom/openvpn-mac-dns#4]
Hi,

I'm using this script along with Tunnelblick. In Tunnelblick I have the DNS option as the default "Use DNS". Using this script works great and solves the issue with the non-existent script on Mac. However, after disconnecting from the VPN does not put back my current network DNS settings. Instead, the values recovered and setup by the script (my company's DNS, etc) remain under Settings, Network, etc. 

Could you please advice on how to fix this? Thank you

**Comment by andrewgdotcom** [comment]
Hi, Eneko.

Sorry for the delay. I haven't seen this error before. Have you added the script as both "up" *and* "down" in the client config file?

**Comment by e9169** [comment]
> Hi, Eneko.
> 
> Sorry for the delay. I haven't seen this error before. Have you added the script as both "up" _and_ "down" in the client config file?

Hi Andrew,

Thank you for the reply. I ended up removing those two lines and everything works smoothly now so I think I won't need the script anymore. Somehow tunnelblick is managing the DNS changes for me now.
