### ISSUE TITLE
Missing installation info

### ISSUE THREAD

**Issue by GoossensMichael** [andrewgdotcom/openvpn-mac-dns#5]
It is not clear how to install this script properly. I am using OpenVpn Connect 3.0.2.

* There is no /etc/openvpn folder, should I make this myself? (did this)
* How does openvpn know about this script and the up and down commands?
* OpenVPN just marks the commands in the logs as "UNUSED OPTIONS"

**Comment by andrewgdotcom** [comment]
Hi, Michael.

Openvpn will know about this script if the client has the following in the client config file:

```
script-security 2
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
```

This is a fairly standard solution for Linux. I'll make sure to add it to the README now.

**Comment by cpboyd** [comment]
Does that go in the `~/Library/Application Support/OpenVPN Connect/profiles/*.ovpn` file?
