### ISSUE TITLE
"Command requires admin privileges." when restoring the DNS config

### ISSUE THREAD

**Issue by aVolpe** [andrewgdotcom/openvpn-mac-dns#8]
At openvpn startup the `networksetup` setup command works correctly:

```
updating dns for Wi-Fi
updating dns for Thunderbolt Bridge
```

But at the stop moment (`down`), it can't restore the DNS with this message:

```
updating dns for Wi-Fi
** Error: Command requires admin privileges.
** Error: Command requires admin privileges.
updating dns for Thunderbolt Bridge
** Error: Command requires admin privileges.
** Error: Command requires admin privileges.
```

### Aditional info

Running the command directly without sudo:

```bash
networksetup -setdnsservers "Wi-Fi" empty
```

Works.

Current config:

```script-security 2
script-security 2
dhcp-option DNS 10.8.X.X
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
```

**Comment by aVolpe** [comment]
The problem was that I had in my OpenVPN file:

```
# Downgrade privileges after initialization (non-Windows only)
user nobody
group nogroup
```

So the down scripts were executed as `nobody` and it doesn't have the required access, removing those lines seems to work.

**Comment by andrewgdotcom** [comment]
Glad to hear you got it sorted! I don't think the script can be made compatible with your privilege-dropping setup, once you become nobody:nogroup there's pretty much nothing that you can do...

**Comment by aVolpe** [comment]
Yes! Maybe dropping to a special user that can only execute that command!

Thanks for the script!.
